### ISSUE TITLE
Update xsd:duration primitive according ISO norm

### ISSUE THREAD

**Issue by ThibautDemasure** [ISyE-FM/Planning#51]
See [wiki](https://en.wikipedia.org/wiki/ISO_8601#Durations).

**Comment by StijnHuysentruyt** [comment]
Added DistributedDuration property as xml:string to workdefinition type

**Comment by ThibautDemasure** [comment]
DistributedDuration handling in issue #55. This is the implementation of the ISO duration instead of value in secs and is not done yet.
